// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc810.Stronghold.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc810.Stronghold.Robot;
import org.usfirst.frc810.Stronghold.RobotMap;

/**
 *
 */
public class DriveStraight extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_Speed;
    private double m_Time;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveStraight(double Speed, double Time) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_Speed = Speed;
        m_Time = Time;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    long startTime;
    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	startTime = System.currentTimeMillis();
    	
    	Robot.drive.setSpeedForArcadePID(m_Speed);
    	double currentAngle = RobotMap.driveGyro.getAngle();
    	if(currentAngle > 180) currentAngle -= 360;
    	Robot.drive.setPIDAngle(currentAngle);
    	Robot.drive.enablePIDRotation();
    
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return System.currentTimeMillis()>= (startTime + (long)(m_Time * 1000));
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drive.setSpeedForArcadePID(0);
    	Robot.drive.disablePIDRotation();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.drive.setSpeedForArcadePID(0);
    	Robot.drive.disablePIDRotation();
    }
}
