// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc810.Stronghold;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import org.usfirst.frc810.Stronghold.subsystems.Arm;

import com.kauailabs.navx.frc.AHRS;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveLeft;
    public static SpeedController driveRight;
    public static RobotDrive driveTankDrive;
    public static CANTalon intakeRoller;
    public static DoubleSolenoid pusherPiston;
    public static Compressor pusherCompressor1;
    public static AnalogPotentiometer armAngle;
    public static CANTalon armHinge;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static AHRS driveGyro;
    public static PIDController drivePID;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeft = new Spark(0);
        LiveWindow.addActuator("Drive", "Left", (Spark) driveLeft);
        
        driveRight = new Spark(1);
        LiveWindow.addActuator("Drive", "Right", (Spark) driveRight);
        
        driveTankDrive = new RobotDrive(driveLeft, driveRight);
        
        driveTankDrive.setSafetyEnabled(true);
        driveTankDrive.setExpiration(0.1);
        driveTankDrive.setSensitivity(0.5);
        driveTankDrive.setMaxOutput(1.0);

        intakeRoller = new CANTalon(2);
        LiveWindow.addActuator("Intake", "Roller", intakeRoller);
        
        pusherPiston = new DoubleSolenoid(0, 7, 6);
        LiveWindow.addActuator("Pusher", "Piston", pusherPiston);
        
        pusherCompressor1 = new Compressor(0);
        
        
        armAngle = new AnalogPotentiometer(0, 1.0, 0.0);
        LiveWindow.addSensor("Arm", "Angle", armAngle);
        
        armHinge = new CANTalon(3);
        LiveWindow.addActuator("Arm", "Hinge", armHinge);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
       
        driveGyro = new AHRS(SPI.Port.kMXP);
        LiveWindow.addSensor("Drive", "Gyro", driveGyro);
        driveGyro.zeroYaw();
        
        intakeRoller.changeControlMode(TalonControlMode.Speed);
        intakeRoller.reverseOutput(false);
    	intakeRoller.configEncoderCodesPerRev(1024);
    	intakeRoller.setPosition(0);
    	
    	
    	 
   
    }
}
